// Jigsaw Notes — App Logic
const DICT_KEY="jigsaw_dict_v3",ENTRIES_KEY="jigsaw_entries_v3",FOLDERS_KEY="jigsaw_folders_v3",RECENT_KEY="jigsaw_recent_v3",RECENT_NOTES_KEY="jigsaw_recent_notes_v3",CATS_KEY="jigsaw_cats_v3",PINNED_NOTES_KEY="jigsaw_pinned_v3",BIN_KEY="jigsaw_bin_v3",BIN_TTL_DAYS=15;
function migrateDict(r){if(!r)return[{id:'sh_0',key:'mtg',val:'meeting',folders:null},{id:'sh_1',key:'tmrw',val:'tomorrow',folders:null},{id:'sh_2',key:'w/',val:'with',folders:null}];if(Array.isArray(r))return r;return Object.entries(r).map(([k,v],i)=>({id:'sh_lg_'+i,key:k,val:v,folders:null}));}
let dict=migrateDict(JSON.parse(localStorage.getItem(DICT_KEY)));
let folders=JSON.parse(localStorage.getItem(FOLDERS_KEY))||[{id:'root',name:'Home',parentId:null,shorthandEnabled:true}];
folders=folders.map(f=>{if(f.shorthandEnabled===undefined)f.shorthandEnabled=true;return f;});
let recentFolders=JSON.parse(localStorage.getItem(RECENT_KEY))||['root'];
let recentNotes=JSON.parse(localStorage.getItem(RECENT_NOTES_KEY))||[];
let pinnedNotes=JSON.parse(localStorage.getItem(PINNED_NOTES_KEY))||[];
let recycleBin=JSON.parse(localStorage.getItem(BIN_KEY))||[];
let categories=JSON.parse(localStorage.getItem(CATS_KEY))||[{id:'cat_happening',name:'Happening',prefix:''},{id:'cat_todo',name:'To Do',prefix:'!'},{id:'cat_question',name:'Question',prefix:'?'}];
let entries=JSON.parse(localStorage.getItem(ENTRIES_KEY))||[];
entries=entries.map(e=>{if(e.catId&&!e.catIds){e.catIds=[e.catId];delete e.catId;}return e;});
let currentFolderId='root',currentNoteId=null,currentView='rapid',selectMode=false,selectedIds=new Set(),searchActive=false,_modalStack=[],dictSelectedIds=new Set(),dictEditingId=null,_faTargetIds=[],_faChecked=null,mediaRecorder,audioChunks=[],recordTimer,recordSeconds=0,activeSettingsFolderId=null,dbPromise=null;
function saveAll(){localStorage.setItem(DICT_KEY,JSON.stringify(dict));localStorage.setItem(ENTRIES_KEY,JSON.stringify(entries));localStorage.setItem(FOLDERS_KEY,JSON.stringify(folders));localStorage.setItem(RECENT_KEY,JSON.stringify(recentFolders));localStorage.setItem(RECENT_NOTES_KEY,JSON.stringify(recentNotes));localStorage.setItem(CATS_KEY,JSON.stringify(categories));localStorage.setItem(PINNED_NOTES_KEY,JSON.stringify(pinnedNotes));localStorage.setItem(BIN_KEY,JSON.stringify(recycleBin));updateBinBadge();}
function softDeleteEntry(e){e.deletedAt=Date.now();recycleBin.unshift(e);}
function daysLeft(d){return Math.max(0,Math.ceil(BIN_TTL_DAYS-(Date.now()-d)/(1000*60*60*24)));}
function autoPurgeBin(){const c=Date.now()-BIN_TTL_DAYS*24*60*60*1000;recycleBin.filter(e=>e.deletedAt<c).forEach(e=>{if(e.audioId)deleteBlob('audio',e.audioId);if(e.imageId)deleteBlob('images',e.imageId);});recycleBin=recycleBin.filter(e=>e.deletedAt>=c);saveAll();}
function updateBinBadge(){const b=document.getElementById('binBadge');if(!b)return;const c=recycleBin.length;if(c>0){b.textContent=c>9?'9+':c;b.style.display='inline-flex';}else b.style.display='none';}
function renderBinModal(){const body=document.getElementById('binModalBody');body.innerHTML='';if(recycleBin.length===0){body.innerHTML='<div style="color:var(--text-muted);font-size:13px;text-align:center;padding:24px 0;">Recycle bin is empty</div>';return;}const eb=document.createElement('button');eb.className='bin-empty-btn';eb.textContent='Empty bin ('+recycleBin.length+')';eb.onclick=()=>{if(!confirm('Permanently delete all '+recycleBin.length+' note(s)?'))return;recycleBin.forEach(e=>{if(e.audioId)deleteBlob('audio',e.audioId);if(e.imageId)deleteBlob('images',e.imageId);});recycleBin=[];saveAll();renderBinModal();showToast('Bin emptied');};body.appendChild(eb);const n=document.createElement('div');n.style.cssText='font-size:11px;color:var(--text-muted);margin-bottom:10px;';n.textContent='Notes are permanently deleted after 15 days.';body.appendChild(n);recycleBin.forEach(entry=>{const rem=daysLeft(entry.deletedAt);const item=document.createElement('div');item.className='bin-item';item.innerHTML='<div class="bin-item-content"><div class="bin-item-title">'+escapeHTML(entry.title||'Untitled')+'</div><div class="bin-item-meta">Deleted '+new Date(entry.deletedAt).toLocaleDateString()+' \u00b7 '+escapeHTML(getFolderName(entry.folderId))+'</div><div class="bin-actions"><button class="bin-action-btn restore" data-id="'+entry.id+'">Restore</button><button class="bin-action-btn perm-del" data-id="'+entry.id+'">Delete</button></div></div><div class="bin-item-days '+(rem>7?'safe':'')+'" >'+rem+'d</div>';item.querySelector('.restore').onclick=()=>{recycleBin=recycleBin.filter(e=>e.id!==entry.id);delete entry.deletedAt;entries.unshift(entry);saveAll();renderBinModal();renderRapidView();showToast('Note restored');};item.querySelector('.perm-del').onclick=()=>{if(!confirm('Permanently delete this note?'))return;if(entry.audioId)deleteBlob('audio',entry.audioId);if(entry.imageId)deleteBlob('images',entry.imageId);recycleBin=recycleBin.filter(e=>e.id!==entry.id);saveAll();renderBinModal();showToast('Note permanently deleted');};body.appendChild(item);});}
const DB_NAME='jigsaw_media_v1',DB_VERSION=1;
function openMediaDB(){if(dbPromise)return dbPromise;dbPromise=new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains('audio'))d.createObjectStore('audio');if(!d.objectStoreNames.contains('images'))d.createObjectStore('images');};r.onsuccess=e=>res(e.target.result);r.onerror=e=>rej(e.target.error);});return dbPromise;}
async function saveBlob(s,id,b){const db=await openMediaDB();return new Promise((res,rej)=>{const tx=db.transaction(s,'readwrite');tx.objectStore(s).put(b,id);tx.oncomplete=()=>res();tx.onerror=e=>rej(e.target.error);});}
async function getBlob(s,id){const db=await openMediaDB();return new Promise((res,rej)=>{const tx=db.transaction(s,'readonly');const r=tx.objectStore(s).get(id);r.onsuccess=()=>res(r.result);r.onerror=e=>rej(e.target.error);});}
async function deleteBlob(s,id){const db=await openMediaDB();return new Promise((res,rej)=>{const tx=db.transaction(s,'readwrite');tx.objectStore(s).delete(id);tx.oncomplete=()=>res();tx.onerror=e=>rej(e.target.error);});}
function updateRecordTime(){const m=Math.floor(recordSeconds/60).toString().padStart(2,'0'),s=(recordSeconds%60).toString().padStart(2,'0');document.getElementById('recordTime').textContent=m+':'+s;}
async function startRecording(){try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});mediaRecorder=new MediaRecorder(stream);audioChunks=[];mediaRecorder.ondataavailable=e=>{if(e.data.size>0)audioChunks.push(e.data);};mediaRecorder.onstop=async()=>{const blob=new Blob(audioChunks,{type:'audio/webm'});const audioId='aud_'+Date.now().toString(36);await saveBlob('audio',audioId,blob);if(currentView==='editor'&&currentNoteId){const note=entries.find(e=>e.id===currentNoteId);if(note){if(note.audioId)deleteBlob('audio',note.audioId);note.audioId=audioId;if(!note.title&&!note.content)note.title='Voice memo';saveAll();updateEditorUI();}}else{entries.unshift({id:'n_'+Date.now().toString(36),folderId:currentFolderId,catIds:[categories[0].id],ts:Date.now(),title:'Voice memo',content:'',audioId:audioId});saveAll();renderRapidView();showToast('Voice memo saved');}stream.getTracks().forEach(t=>t.stop());document.getElementById('recordingOverlay').style.display='none';clearInterval(recordTimer);};document.getElementById('recordingOverlay').style.display='flex';recordSeconds=0;updateRecordTime();recordTimer=setInterval(()=>{recordSeconds++;updateRecordTime();},1000);mediaRecorder.start();}catch(err){console.error(err);showToast('Microphone access denied');}}
function stopRecording(){if(mediaRecorder&&mediaRecorder.state==='recording')mediaRecorder.stop();}
function getCat(id){return categories.find(c=>c.id===id)||categories[0];}
function getCats(ids){return(ids||[]).map(id=>getCat(id));}
function getFolderName(id){const f=folders.find(f=>f.id===id);return f?f.name:'Home';}
function escapeHTML(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML;}
function classifyText(text){let t=text.trim(),catIds=[];const sc=[...categories].filter(c=>c.prefix).sort((a,b)=>b.prefix.length-a.prefix.length);let m=true;while(m){m=false;for(let cat of sc){if(t.startsWith(cat.prefix)){catIds.push(cat.id);t=t.slice(cat.prefix.length).trim();m=true;break;}}}catIds=[...new Set(catIds)];if(catIds.length===0)catIds=[categories[0].id];return{catIds,clean:t||'Empty'};}
function isEntryAllowedInFolder(entry,folderId){if(!entry.folders||entry.folders.length===0)return true;let cur=folderId;while(cur){if(entry.folders.includes(cur))return true;const f=folders.find(f=>f.id===cur);cur=f?f.parentId:null;}return false;}
function expandShorthand(text){const folder=folders.find(f=>f.id===currentFolderId);if(folder&&folder.shorthandEnabled===false)return text;const allowed=dict.filter(e=>isEntryAllowedInFolder(e,currentFolderId));let words=text.split(/(\s+)/);words=words.map(tok=>{const e=allowed.find(e=>e.key.toLowerCase()===tok.trim().toLowerCase());return e?e.val:tok;});return words.join('');}
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800);}
function linkifyText(text){return text.replace(/(https?:\/\/[^\s<>"']+)/gi,'<a href="$1" target="_blank" rel="noopener" onclick="event.stopPropagation()">$1</a>');}
function renderChecklistPreview(content){const lines=content.split('\n');const ci=lines.filter(l=>/^\s*\[([ x])\]/i.test(l));if(ci.length===0)return'';let h='<div class="entry-checklist">';ci.slice(0,3).forEach(line=>{const done=/^\s*\[x\]/i.test(line);const text=line.replace(/^\s*\[([ x])\]\s*/i,'').trim();h+='<div class="entry-checklist-item '+(done?'done':'')+'"><span>'+(done?'\u2611':'\u2610')+'</span> '+escapeHTML(text)+'</div>';});if(ci.length>3)h+='<div class="entry-checklist-item">\u2026 '+(ci.length-3)+' more</div>';h+='</div>';return h;}
function startOrOpenEmptyNote(){let en=entries.find(e=>e.folderId===currentFolderId&&e.content.trim()==='');if(en){currentNoteId=en.id;document.getElementById('noteContent').value=en.content;}else{currentNoteId='n_'+Date.now().toString(36);entries.unshift({id:currentNoteId,folderId:currentFolderId,catIds:[categories[0].id],ts:Date.now(),title:'',content:''});document.getElementById('noteContent').value='';}updateRecentNotes(currentNoteId);updateEditorUI();setTimeout(()=>document.getElementById('noteContent').focus(),100);}
function openNote(id){const note=entries.find(e=>e.id===id);if(!note)return;currentNoteId=id;currentFolderId=note.folderId;document.getElementById('noteContent').value=note.content;updateRecentNotes(currentNoteId);updateEditorUI();switchView('editor');}
function updateRecentNotes(id){recentNotes=recentNotes.filter(n=>n!==id);recentNotes.unshift(id);if(recentNotes.length>3)recentNotes.pop();saveAll();}
function autoSaveNote(){if(!currentNoteId)return;const content=document.getElementById('noteContent').value;const note=entries.find(e=>e.id===currentNoteId);if(note){if(note.content.trim()===''&&content.trim()!==''){const{catIds}=classifyText(content.split('\n')[0]);note.catIds=catIds;}note.content=content;note.title=content.split('\n')[0].trim()||'';note.ts=Date.now();saveAll();updateEditorUI();}}
function updateEditorUI(){if(!currentNoteId)return;const note=entries.find(e=>e.id===currentNoteId);if(!note)return;document.getElementById('editorFolderBadge').textContent=getFolderName(note.folderId);const tc=document.getElementById('editorTagsContainer');tc.innerHTML='';getCats(note.catIds).forEach(cat=>{const tag=document.createElement('span');tag.className='tag-badge';tag.textContent=cat.name;tag.addEventListener('click',()=>{renderSelectModals();toggleModal('selectCatModal',true);});tc.appendChild(tag);});const ab=document.createElement('span');ab.className='tag-badge';ab.textContent='+';ab.style.background='transparent';ab.style.color='var(--text-muted)';ab.addEventListener('click',()=>{renderSelectModals();toggleModal('selectCatModal',true);});tc.appendChild(ab);const pb=document.getElementById('editorPinBtn');if(pinnedNotes.includes(currentNoteId))pb.classList.add('is-pinned');else pb.classList.remove('is-pinned');const ac=document.getElementById('editorAudioContainer');if(note.audioId||note.imageId){ac.style.display='block';ac.innerHTML='';if(note.imageId){getBlob('images',note.imageId).then(blob=>{if(blob){const url=URL.createObjectURL(blob);const img=document.createElement('img');img.src=url;img.style='max-width:100%;max-height:300px;border-radius:8px;display:block;margin-bottom:8px;';ac.appendChild(img);}});}if(note.audioId){getBlob('audio',note.audioId).then(blob=>{if(blob){const url=URL.createObjectURL(blob);const aud=document.createElement('audio');aud.controls=true;aud.src=url;aud.style='width:100%;height:32px;display:block;';ac.appendChild(aud);}});}}else{ac.style.display='none';ac.innerHTML='';}}
function addRapidEntry(){const input=document.getElementById('rapidEntry');const raw=input.value;if(!raw.trim())return;const{catIds,clean}=classifyText(raw);const expanded=expandShorthand(clean);entries.unshift({id:'n_'+Date.now().toString(36),folderId:currentFolderId,catIds,ts:Date.now(),title:expanded.split('\n')[0],content:expanded});saveAll();input.value='';renderRapidView();showToast('Added to '+getCats(catIds).map(c=>c.name).join(', '));input.focus();}
function switchView(v){currentView=v;document.getElementById('view-editor').classList.toggle('hidden',v!=='editor');document.getElementById('view-rapid').classList.toggle('hidden',v!=='rapid');document.getElementById('bottom-dock').classList.toggle('editor-mode',v==='editor');document.getElementById('toggleNoteBtn').classList.toggle('active',v==='editor');document.getElementById('toggleRapidBtn').classList.toggle('active',v==='rapid');if(v==='rapid'){document.getElementById('appTitle').textContent=getFolderName(currentFolderId);exitSelectMode();renderRapidView();}else{document.getElementById('appTitle').textContent='Jigsaw Notes';if(!currentNoteId)startOrOpenEmptyNote();}}
function renderRapidView(){const container=document.getElementById('dynamicListsContainer');container.innerHTML='';const sq=searchActive?document.getElementById('searchInput').value.trim().toLowerCase():'';if(searchActive&&sq){renderSearchResults(sq,container);return;}categories.forEach(cat=>{const items=entries.filter(e=>e.catIds.includes(cat.id)&&e.folderId===currentFolderId&&e.content.trim()!=='');const sec=document.createElement('section');sec.className='list';sec.dataset.catId=cat.id;sec.addEventListener('dragover',e=>{e.preventDefault();sec.classList.add('drag-over');});sec.addEventListener('dragleave',()=>sec.classList.remove('drag-over'));sec.addEventListener('drop',e=>{e.preventDefault();sec.classList.remove('drag-over');const eid=e.dataTransfer.getData('text/plain');const entry=entries.find(en=>en.id===eid);if(entry&&!entry.catIds.includes(cat.id)){if(e.shiftKey){entry.catIds=[cat.id];}else{entry.catIds.push(cat.id);}saveAll();renderRapidView();}});const hdr=document.createElement('div');hdr.className='list-header';hdr.innerHTML='<div class="list-title">'+escapeHTML(cat.name)+(cat.prefix?'<span style="font-size:9.5px;font-weight:500;opacity:0.55;letter-spacing:0;margin-left:2px;">'+escapeHTML(cat.prefix)+'</span>':'')+'</div><span class="list-count">'+items.length+'</span>';hdr.addEventListener('click',()=>{const isF=container.dataset.filteredCat===cat.id;if(isF){delete container.dataset.filteredCat;container.querySelectorAll('section.list').forEach(s=>s.style.display='');showToast('Showing all');}else{container.dataset.filteredCat=cat.id;container.querySelectorAll('section.list').forEach(s=>{s.style.display=s.dataset.catId===cat.id?'':'none';});showToast('Filtered: '+cat.name);}});sec.appendChild(hdr);const ed=document.createElement('div');ed.className='entries';if(items.length===0){ed.innerHTML='<div class="empty">Nothing here yet.</div>';}else{items.forEach(e=>renderEntryCard(e,ed));}sec.appendChild(ed);container.appendChild(sec);});}
function renderEntryCard(e,parent,showFolder){const div=document.createElement('div');div.className='entry'+(selectedIds.has(e.id)?' selected':'');div.draggable=!selectMode;div.dataset.entryId=e.id;if(!selectMode){div.addEventListener('dragstart',ev=>{ev.dataTransfer.setData('text/plain',e.id);});}const preview=e.content.split('\n').slice(1).join(' ').trim();const clHtml=renderChecklistPreview(e.content);const prevHtml=preview?linkifyText(escapeHTML(preview)):'';const folderTag=showFolder?'<span class="search-result-folder">in '+escapeHTML(getFolderName(e.folderId))+'</span>':'';const multiTag=e.catIds&&e.catIds.length>1?'<span class="search-result-folder" style="color:var(--color-primary);margin-left:4px;">+'+(e.catIds.length-1)+'</span>':'';let mHtml='';if(e.imageId)mHtml+='<div id="img-c-'+e.id+'" style="margin-top:8px;">Loading\u2026</div>';if(e.audioId)mHtml+='<div id="aud-c-'+e.id+'" style="margin-top:8px;">Loading\u2026</div>';div.innerHTML='<div class="select-check">'+(selectedIds.has(e.id)?'\u2713':'')+'</div><div class="entry-content"><div class="entry-title">'+escapeHTML(e.title||'Untitled')+folderTag+multiTag+'</div>'+(clHtml||(prevHtml?'<div class="entry-preview">'+prevHtml+'</div>':''))+mHtml+'</div><div class="del">\u2715</div>';div.addEventListener('click',ev=>{if(selectMode){ev.preventDefault();toggleSelectEntry(e.id,div);return;}openNote(e.id);});let lpt;div.addEventListener('touchstart',()=>{lpt=setTimeout(()=>{enterSelectMode();toggleSelectEntry(e.id,div);},500);},{passive:true});div.addEventListener('touchend',()=>clearTimeout(lpt));div.addEventListener('touchmove',()=>clearTimeout(lpt));div.querySelector('.del').addEventListener('click',ev=>{ev.stopPropagation();if(confirm('Move to recycle bin?')){const entry=entries.find(en=>en.id===e.id);if(entry)softDeleteEntry(entry);entries=entries.filter(en=>en.id!==e.id);pinnedNotes=pinnedNotes.filter(id=>id!==e.id);recentNotes=recentNotes.filter(id=>id!==e.id);saveAll();renderRapidView();showToast('Moved to bin');}});parent.appendChild(div);if(e.imageId){getBlob('images',e.imageId).then(blob=>{if(blob){const el=document.getElementById('img-c-'+e.id);if(el){const url=URL.createObjectURL(blob);el.innerHTML='<img src="'+url+'" style="max-width:100%;max-height:200px;border-radius:8px;display:block;">';}}}); }if(e.audioId){getBlob('audio',e.audioId).then(blob=>{if(blob){const el=document.getElementById('aud-c-'+e.id);if(el){const url=URL.createObjectURL(blob);el.innerHTML='<audio controls src="'+url+'" style="width:100%;height:32px;display:block;" onclick="event.stopPropagation()"></audio>';}}});}}
function renderSearchResults(query,container){const results=entries.filter(e=>{if(e.content.trim()==='')return false;return(e.title+' '+e.content).toLowerCase().includes(query);});const sec=document.createElement('section');sec.className='list';const hdr=document.createElement('div');hdr.className='list-header';hdr.innerHTML='<div class="list-title">Search results</div><span class="list-count">'+results.length+'</span>';sec.appendChild(hdr);const ed=document.createElement('div');ed.className='entries';if(results.length===0){ed.innerHTML='<div class="empty">No notes match "'+escapeHTML(query)+'"</div>';}else{results.forEach(e=>renderEntryCard(e,ed,true));}sec.appendChild(ed);container.appendChild(sec);}
function enterSelectMode(){if(selectMode)return;selectMode=true;selectedIds.clear();document.body.classList.add('select-mode');document.getElementById('selectBar').classList.add('open');document.getElementById('bottom-dock').style.display='none';updateSelectCount();}
function exitSelectMode(){selectMode=false;selectedIds.clear();document.body.classList.remove('select-mode');document.getElementById('selectBar').classList.remove('open');document.getElementById('bottom-dock').style.display='';document.querySelectorAll('.entry.selected').forEach(el=>el.classList.remove('selected'));}
function toggleSelectEntry(id,el){if(selectedIds.has(id)){selectedIds.delete(id);el.classList.remove('selected');el.querySelector('.select-check').textContent='';}else{selectedIds.add(id);el.classList.add('selected');el.querySelector('.select-check').textContent='\u2713';}updateSelectCount();}
function updateSelectCount(){document.getElementById('selectCount').textContent=selectedIds.size+' selected';}
function renderSidebarPinnedNotes(){const box=document.getElementById('pinnedNotesBox'),list=document.getElementById('pinnedNotesList');list.innerHTML='';const vn=pinnedNotes.filter(nId=>entries.some(e=>e.id===nId));if(vn.length>0){box.style.display='block';vn.forEach(nId=>{const note=entries.find(e=>e.id===nId);const div=document.createElement('div');div.className='pinned-note-item';div.textContent=note.title||'Untitled';div.onclick=()=>{openNote(nId);toggleModal('sidebar',false);};list.appendChild(div);});}else box.style.display='none';}
function renderSidebarRecentNotes(){const box=document.getElementById('recentNotesBox'),list=document.getElementById('recentNotesList');list.innerHTML='';const vn=recentNotes.filter(nId=>entries.some(e=>e.id===nId));if(vn.length>0){box.style.display='block';vn.forEach(nId=>{const note=entries.find(e=>e.id===nId);const div=document.createElement('div');div.className='recent-note-item';div.textContent=note.title||'Untitled';div.onclick=()=>{openNote(nId);toggleModal('sidebar',false);};list.appendChild(div);});}else box.style.display='none';}
function renderSidebarFolders(){renderSidebarPinnedNotes();renderSidebarRecentNotes();const tree=document.getElementById('folderTree'),ps=document.getElementById('newFolderParent');tree.innerHTML='';ps.innerHTML='';const rb=document.getElementById('recentFoldersBox'),rc=document.getElementById('recentChips');rc.innerHTML='';const vr=recentFolders.filter(rId=>folders.some(f=>f.id===rId));if(vr.length>0){rb.style.display='block';vr.forEach(rId=>{const chip=document.createElement('div');chip.className='recent-chip '+(rId===currentFolderId&&currentView==='rapid'?'active':'');chip.textContent=getFolderName(rId);chip.onclick=()=>{currentFolderId=rId;updateRecents(rId);toggleModal('sidebar',false);switchView('rapid');};rc.appendChild(chip);});}else rb.style.display='none';function drawFolder(folder,depth){const div=document.createElement('div');div.className='folder-item folder-indent-'+depth+' '+(folder.id===currentFolderId&&currentView==='rapid'?'active':'');div.innerHTML='<span>'+escapeHTML(folder.name)+'</span><div style="display:flex;gap:4px;"><span class="f-settings">\u2699</span><span class="f-del">\u2715</span></div>';div.onclick=ev=>{if(ev.target.classList.contains('f-del')){if(!confirm('Delete folder? Notes move to Home.'))return;let toDel=[];function cd(pid){toDel.push(pid);folders.filter(f=>f.parentId===pid).forEach(c=>cd(c.id));}cd(folder.id);entries.forEach(en=>{if(toDel.includes(en.folderId))en.folderId='root';});folders=folders.filter(f=>!toDel.includes(f.id));recentFolders=recentFolders.filter(rId=>!toDel.includes(rId));if(toDel.includes(currentFolderId))currentFolderId='root';saveAll();renderSidebarFolders();}else if(ev.target.classList.contains('f-settings')){openFolderSettings(folder.id);}else{currentFolderId=folder.id;updateRecents(folder.id);toggleModal('sidebar',false);switchView('rapid');}};tree.appendChild(div);if(depth<2)ps.add(new Option('\u2014'.repeat(depth)+folder.name,folder.id));folders.filter(f=>f.parentId===folder.id).forEach(c=>drawFolder(c,depth+1));}const root=folders.find(f=>f.id==='root');if(root)drawFolder(root,0);}
function updateRecents(id){recentFolders=recentFolders.filter(fId=>fId!==id);recentFolders.unshift(id);if(recentFolders.length>3)recentFolders.pop();saveAll();}
function openFolderSettings(folderId){activeSettingsFolderId=folderId;const folder=folders.find(f=>f.id===folderId);if(!folder)return;document.getElementById('folderSettingsTitle').textContent=folder.name+' settings';document.getElementById('folderShorthandToggle').checked=folder.shorthandEnabled!==false;toggleModal('folderSettingsModal',true);}
function getDictFolderLabel(e){if(!e.folders||e.folders.length===0)return'All folders';return e.folders.length+' folder'+(e.folders.length!==1?'s':'');}
function renderDict(){const list=document.getElementById('dictList');list.innerHTML='';const bar=document.getElementById('dictMultiBar');if(dictSelectedIds.size>0){bar.classList.add('visible');document.getElementById('dictMultiCount').textContent=dictSelectedIds.size+' selected';}else bar.classList.remove('visible');dict.forEach(entry=>{const isSel=dictSelectedIds.has(entry.id),isSc=entry.folders&&entry.folders.length>0;const row=document.createElement('div');row.className='dict-row'+(isSel?' selected':'');row.innerHTML='<div class="dict-check">'+(isSel?'\u2713':'')+'</div><div class="dict-kv"><b>'+escapeHTML(entry.key)+'</b> <span style="color:var(--text-muted)">\u2192</span> '+escapeHTML(entry.val)+'</div><span class="dict-folder-chip '+(isSc?'scoped':'')+'">'+escapeHTML(getDictFolderLabel(entry))+'</span><button class="dict-del-btn">\u2715</button>';row.querySelector('.dict-check').addEventListener('click',ev=>{ev.stopPropagation();if(dictSelectedIds.has(entry.id))dictSelectedIds.delete(entry.id);else dictSelectedIds.add(entry.id);renderDict();});row.querySelector('.dict-kv').addEventListener('click',()=>openDictEdit(entry.id));row.querySelector('.dict-folder-chip').addEventListener('click',ev=>{ev.stopPropagation();openFolderAccess([entry.id]);});row.querySelector('.dict-del-btn').addEventListener('click',ev=>{ev.stopPropagation();if(!confirm('Delete "'+entry.key+'"?'))return;dict=dict.filter(e=>e.id!==entry.id);dictSelectedIds.delete(entry.id);saveAll();renderDict();});list.appendChild(row);});if(dict.length===0)list.innerHTML='<div style="color:var(--text-muted);font-size:13px;padding:12px 2px;">No shorthands yet.</div>';}
function openDictEdit(id){dictEditingId=id;const sec=document.getElementById('dictEditSection');sec.style.display='block';if(id===null){document.getElementById('dictKey').value='';document.getElementById('dictVal').value='';updateDictFolderLabel(null);}else{const entry=dict.find(e=>e.id===id);if(entry){document.getElementById('dictKey').value=entry.key;document.getElementById('dictVal').value=entry.val;updateDictFolderLabel(entry.folders);}}document.getElementById('dictKey').focus();}
function updateDictFolderLabel(fl){document.getElementById('dictFolderAccessLabel').textContent='Allowed in: '+(!fl||fl.length===0?'All folders':fl.length+' folder'+(fl.length!==1?'s':''));}
function isInheritedFA(folderId){if(!_faChecked)return false;const f=folders.find(f=>f.id===folderId);if(!f||!f.parentId)return false;let cur=f.parentId;while(cur){if(_faChecked.includes(cur))return true;const p=folders.find(f=>f.id===cur);cur=p?p.parentId:null;}return false;}
function openFolderAccess(ids){_faTargetIds=ids;if(ids.length===1){const e=dict.find(e=>e.id===ids[0]);_faChecked=e&&e.folders?[...e.folders]:null;}else _faChecked=null;renderFolderAccessModal();toggleModal('folderAccessModal',true);}
function renderFolderAccessModal(){const list=document.getElementById('folderAccessList');list.innerHTML='';const ab=document.createElement('button');ab.className='fa-allow-all-btn';ab.textContent='Allow in all folders';ab.onclick=()=>{_faChecked=null;applyFolderAccess();toggleModal('folderAccessModal',false);};list.appendChild(ab);const hint=document.createElement('div');hint.style.cssText='font-size:11px;color:var(--text-muted);margin-bottom:10px;line-height:1.5;';hint.textContent='Sub-folders inherit automatically.';list.appendChild(hint);function drawFA(folder,depth){const isCh=_faChecked!==null&&_faChecked.includes(folder.id),isIn=!isCh&&isInheritedFA(folder.id);const row=document.createElement('div');row.className='fa-row'+(isCh?' checked':'');row.style.paddingLeft=(12+depth*18)+'px';const chk=document.createElement('div');chk.className='fa-check'+(isCh?' checked':(isIn?' inherited':''));chk.textContent=(isCh||isIn)?'\u2713':'';const lbl=document.createElement('div');lbl.style.cssText='font-size:13px;flex:1;color:'+(isIn?'var(--text-muted)':'var(--color-foreground)')+';';lbl.textContent=folder.name+(isIn?' (inherited)':'');row.appendChild(chk);row.appendChild(lbl);row.onclick=()=>{if(_faChecked===null){_faChecked=[folder.id];}else if(_faChecked.includes(folder.id)){_faChecked=_faChecked.filter(id=>id!==folder.id);if(_faChecked.length===0)_faChecked=null;}else _faChecked.push(folder.id);renderFolderAccessModal();};list.appendChild(row);folders.filter(f=>f.parentId===folder.id).forEach(c=>drawFA(c,depth+1));}const root=folders.find(f=>f.id==='root');if(root)drawFA(root,0);const applyBtn=document.createElement('button');applyBtn.className='fa-apply-btn';applyBtn.textContent='Apply';applyBtn.onclick=()=>{applyFolderAccess();toggleModal('folderAccessModal',false);};list.appendChild(applyBtn);}
function applyFolderAccess(){_faTargetIds.forEach(id=>{const e=dict.find(e=>e.id===id);if(e)e.folders=_faChecked?[..._faChecked]:null;});if(dictEditingId!==null&&_faTargetIds.includes(dictEditingId)){const e=dict.find(e=>e.id===dictEditingId);if(e)updateDictFolderLabel(e.folders);}saveAll();renderDict();}
function renderCategories(){const list=document.getElementById('catList');list.innerHTML='';categories.forEach(c=>{const row=document.createElement('div');row.className='list-item';const nameDiv=document.createElement('div');nameDiv.style.flex='1';nameDiv.innerHTML='<b>'+escapeHTML(c.name)+'</b>'+(c.prefix?' <span style="color:var(--text-muted)">('+escapeHTML(c.prefix)+')</span>':'');const del=document.createElement('span');del.className='del';del.textContent='\u2715';del.onclick=ev=>{ev.stopPropagation();if(categories.length===1){showToast('Need at least 1 category');return;}categories=categories.filter(cat=>cat.id!==c.id);entries.forEach(en=>{if(en.catIds&&en.catIds.includes(c.id)){en.catIds=en.catIds.filter(id=>id!==c.id);if(en.catIds.length===0)en.catIds=[categories[0].id];}});saveAll();renderCategories();};row.appendChild(nameDiv);row.appendChild(del);row.onclick=()=>{document.getElementById('catName').value=c.name;document.getElementById('catPrefix').value=c.prefix;};list.appendChild(row);});}
function renderSelectModals(){const catList=document.getElementById('selectCatList');catList.innerHTML='';const note=entries.find(e=>e.id===currentNoteId);if(!note)return;categories.forEach(c=>{const row=document.createElement('div');row.className='list-item';const isSel=note.catIds&&note.catIds.includes(c.id);const nameDiv=document.createElement('div');nameDiv.style.flex='1';nameDiv.innerHTML='<b>'+escapeHTML(c.name)+'</b>';const chk=document.createElement('div');chk.style.cssText='display:flex;align-items:center;justify-content:center;width:22px;height:22px;border-radius:11px;opacity:'+(isSel?1:0.25)+';background:'+(isSel?'var(--color-primary)':'transparent')+';border:1px solid var(--color-primary);color:'+(isSel?'var(--color-primary-foreground)':'var(--color-primary)')+';';chk.textContent=isSel?'\u2713':'';row.appendChild(nameDiv);row.appendChild(chk);row.onclick=()=>{if(note.catIds.includes(c.id)){note.catIds=note.catIds.filter(id=>id!==c.id);if(note.catIds.length===0)note.catIds=[categories[0].id];}else note.catIds.push(c.id);saveAll();updateEditorUI();renderSelectModals();};catList.appendChild(row);});const fList=document.getElementById('selectFolderList');fList.innerHTML='';folders.forEach(f=>{const row=document.createElement('div');row.className='list-item';const b=document.createElement('b');b.textContent=f.name;row.appendChild(b);row.onclick=()=>{const n=entries.find(e=>e.id===currentNoteId);if(n){n.folderId=f.id;saveAll();updateEditorUI();}toggleModal('selectFolderModal',false);};fList.appendChild(row);});}
function toggleModal(id,show){const el=document.getElementById(id),ov=document.getElementById('mainOverlay');if(show){document.querySelectorAll('.sidebar, .modal').forEach(m=>m.classList.remove('open'));el.classList.add('open');ov.classList.add('open');_modalStack.push(id);history.pushState({modal:id},'');}else{el.classList.remove('open');ov.classList.remove('open');_modalStack=_modalStack.filter(m=>m!==id);if(history.state&&history.state.modal===id)history.back();}}
function closeAllOverlays(){document.querySelectorAll('.sidebar, .modal').forEach(m=>m.classList.remove('open'));document.getElementById('mainOverlay').classList.remove('open');_modalStack=[];}
function formatText(marker){const ta=document.getElementById('noteContent'),start=ta.selectionStart,end=ta.selectionEnd,val=ta.value,mLen=marker.length,selected=val.slice(start,end);if(start>=mLen&&end<=val.length-mLen&&val.slice(start-mLen,start)===marker&&val.slice(end,end+mLen)===marker){ta.value=val.slice(0,start-mLen)+selected+val.slice(end+mLen);ta.setSelectionRange(start-mLen,end-mLen);ta.focus();autoSaveNote();return;}if(selected){ta.value=val.slice(0,start)+marker+selected+marker+val.slice(end);ta.setSelectionRange(start+mLen,end+mLen);}else{ta.value=val.slice(0,start)+marker+marker+val.slice(start);ta.setSelectionRange(start+mLen,start+mLen);}ta.focus();autoSaveNote();}

window.__jigsawInit = function() {
  window.addEventListener('popstate', e => { const oo = document.querySelector('.sidebar.open, .modal.open'); if (oo) { closeAllOverlays(); return; } if (currentView === 'editor') { switchView('rapid'); history.pushState({view:'rapid'}, ''); return; } history.pushState({view:'rapid'}, ''); });
  history.replaceState({view:'rapid'}, '');
  document.getElementById('mainOverlay').addEventListener('click', () => { closeAllOverlays(); if (history.state && history.state.modal) history.back(); });
  document.getElementById('menuBtn').addEventListener('click', () => { renderSidebarFolders(); toggleModal('sidebar', true); });
  document.getElementById('closeSidebarBtn').addEventListener('click', () => toggleModal('sidebar', false));
  document.getElementById('closeDictBtn').addEventListener('click', () => toggleModal('dictModal', false));
  document.getElementById('menuCatsBtn').addEventListener('click', () => { renderCategories(); toggleModal('catModal', true); });
  document.getElementById('closeCatBtn').addEventListener('click', () => toggleModal('catModal', false));
  document.getElementById('closeSelectCatBtn').addEventListener('click', () => toggleModal('selectCatModal', false));
  document.getElementById('closeSelectFolderBtn').addEventListener('click', () => toggleModal('selectFolderModal', false));
  document.getElementById('closeExportBtn').addEventListener('click', () => toggleModal('exportModal', false));
  document.getElementById('closeBulkMoveBtn').addEventListener('click', () => toggleModal('bulkMoveModal', false));
  document.getElementById('closeFolderSettingsBtn').addEventListener('click', () => toggleModal('folderSettingsModal', false));
  document.getElementById('folderShorthandToggle').addEventListener('change', e => { if (!activeSettingsFolderId) return; const folder = folders.find(f => f.id === activeSettingsFolderId); if (folder) { folder.shorthandEnabled = e.target.checked; saveAll(); } });
  document.getElementById('dictFab').addEventListener('click', () => { dictSelectedIds.clear(); dictEditingId = null; document.getElementById('dictEditSection').style.display = 'none'; renderDict(); toggleModal('dictModal', true); });
  document.getElementById('dictAddNewBtn').addEventListener('click', () => { dictEditingId = null; openDictEdit(null); });
  document.getElementById('dictAdd').addEventListener('click', () => { const k = document.getElementById('dictKey').value.trim(), v = document.getElementById('dictVal').value.trim(); if (!k || !v) { showToast('Key and text are required'); return; } if (dictEditingId !== null) { const e = dict.find(e => e.id === dictEditingId); if (e) { e.key = k; e.val = v; } } else { const ne = {id:'sh_'+Date.now().toString(36),key:k,val:v,folders:null}; dict.push(ne); dictEditingId = ne.id; } saveAll(); renderDict(); document.getElementById('dictEditSection').style.display = 'none'; dictEditingId = null; showToast('Shorthand saved'); });
  document.getElementById('dictFolderAccessBtn').addEventListener('click', () => { if (dictEditingId !== null) { openFolderAccess([dictEditingId]); } else { const k = document.getElementById('dictKey').value.trim(), v = document.getElementById('dictVal').value.trim(); if (!k || !v) { showToast('Fill in key and text first'); return; } const tmp = {id:'sh_'+Date.now().toString(36),key:k,val:v,folders:null}; dict.push(tmp); dictEditingId = tmp.id; saveAll(); renderDict(); openFolderAccess([tmp.id]); } });
  document.getElementById('dictMultiCancelBtn').addEventListener('click', () => { dictSelectedIds.clear(); renderDict(); });
  document.getElementById('dictMultiDeleteBtn').addEventListener('click', () => { if (dictSelectedIds.size === 0) return; if (!confirm('Delete '+dictSelectedIds.size+' shorthand(s)?')) return; dict = dict.filter(e => !dictSelectedIds.has(e.id)); dictSelectedIds.clear(); saveAll(); renderDict(); showToast('Deleted'); });
  document.getElementById('dictMultiFoldersBtn').addEventListener('click', () => { if (dictSelectedIds.size === 0) return; openFolderAccess([...dictSelectedIds]); });
  document.getElementById('closeFolderAccessBtn').addEventListener('click', () => toggleModal('folderAccessModal', false));
  document.getElementById('editorFolderBadge').addEventListener('click', () => { renderSelectModals(); toggleModal('selectFolderModal', true); });
  document.getElementById('dockPhotoBtn').addEventListener('click', () => document.getElementById('photoInput').click());
  document.getElementById('editorPhotoBtn').addEventListener('click', () => document.getElementById('photoInput').click());
  document.getElementById('photoInput').addEventListener('change', async e => { const file = e.target.files[0]; if (!file) return; e.target.value = ''; const imgId = 'img_'+Date.now().toString(36); await saveBlob('images', imgId, file); if (currentView === 'editor' && currentNoteId) { const note = entries.find(n => n.id === currentNoteId); if (note) { if (note.imageId) deleteBlob('images', note.imageId); note.imageId = imgId; if (!note.title && !note.content) note.title = 'Photo'; saveAll(); updateEditorUI(); } } else { entries.unshift({id:'n_'+Date.now().toString(36),folderId:currentFolderId,catIds:[categories[0].id],ts:Date.now(),title:'Photo',content:'',imageId:imgId}); saveAll(); renderRapidView(); showToast('Photo saved'); } });
  document.getElementById('dockMicBtn').addEventListener('click', startRecording);
  document.getElementById('editorMicBtn').addEventListener('click', startRecording);
  document.getElementById('stopRecordBtn').addEventListener('click', stopRecording);
  document.getElementById('toggleRapidBtn').addEventListener('click', () => switchView('rapid'));
  document.getElementById('toggleNoteBtn').addEventListener('click', () => switchView('editor'));
  document.getElementById('appTitle').addEventListener('click', () => { renderSidebarFolders(); toggleModal('sidebar', true); });
  document.getElementById('searchToggleBtn').addEventListener('click', () => { const bar = document.getElementById('searchBar'); if (searchActive) { searchActive = false; bar.classList.add('hidden'); document.getElementById('searchInput').value = ''; renderRapidView(); } else { searchActive = true; bar.classList.remove('hidden'); document.getElementById('searchInput').focus(); } });
  document.getElementById('searchClose').addEventListener('click', () => { searchActive = false; document.getElementById('searchBar').classList.add('hidden'); document.getElementById('searchInput').value = ''; renderRapidView(); });
  document.getElementById('searchInput').addEventListener('input', () => { if (searchActive) renderRapidView(); });
  document.getElementById('checklistBtn').addEventListener('click', () => { if (!currentNoteId) return; const ta = document.getElementById('noteContent'), pos = ta.selectionStart, val = ta.value; let ls = val.lastIndexOf('\n', pos-1)+1, le = val.indexOf('\n', pos); if (le === -1) le = val.length; const line = val.slice(ls, le); let nl; if (/^\s*\[x\]/i.test(line)) nl = line.replace(/^(\s*)\[x\]\s*/i, '$1'); else if (/^\s*\[ \]/.test(line)) nl = line.replace('[ ]', '[x]'); else nl = line.replace(/^(\s*)/, '$1[ ] '); ta.value = val.slice(0,ls)+nl+val.slice(le); const np = ls+nl.length; ta.setSelectionRange(np,np); ta.focus(); autoSaveNote(); });
  document.getElementById('selectCancelBtn').addEventListener('click', () => { exitSelectMode(); renderRapidView(); });
  document.getElementById('selectDeleteBtn').addEventListener('click', () => { if (selectedIds.size === 0) return; const count = selectedIds.size; if (!confirm('Move '+count+' note(s) to recycle bin?')) return; entries.forEach(e => { if (selectedIds.has(e.id)) softDeleteEntry(e); }); entries = entries.filter(e => !selectedIds.has(e.id)); pinnedNotes = pinnedNotes.filter(id => !selectedIds.has(id)); recentNotes = recentNotes.filter(id => !selectedIds.has(id)); saveAll(); exitSelectMode(); renderRapidView(); showToast('Moved '+count+' note(s) to bin'); });
  document.getElementById('selectMoveBtn').addEventListener('click', () => { if (selectedIds.size === 0) return; const count = selectedIds.size; const list = document.getElementById('bulkMoveFolderList'); list.innerHTML = ''; folders.forEach(f => { const row = document.createElement('div'); row.className = 'list-item'; const b = document.createElement('b'); b.textContent = f.name; row.appendChild(b); row.onclick = () => { entries.forEach(e => { if (selectedIds.has(e.id)) e.folderId = f.id; }); saveAll(); toggleModal('bulkMoveModal', false); exitSelectMode(); renderRapidView(); showToast('Moved '+count+' note(s) to '+f.name); }; list.appendChild(row); }); toggleModal('bulkMoveModal', true); });
  document.getElementById('exportBtn').addEventListener('click', () => { document.getElementById('exportFolderName').textContent = getFolderName(currentFolderId); toggleModal('exportModal', true); });
  document.getElementById('exportTxtBtn').addEventListener('click', () => { const fe = entries.filter(e => e.folderId === currentFolderId && e.content.trim() !== ''); if (fe.length === 0) { showToast('No notes to export'); return; } const fn = getFolderName(currentFolderId); let txt = '=== '+fn+' ===\nExported: '+new Date().toLocaleString()+'\n\n'; fe.forEach((e,i) => { const cn = getCats(e.catIds).map(c=>c.name).join(', '); txt += '--- '+(i+1)+'. ['+cn+'] ---\n'+e.content+'\n\n'; }); const blob = new Blob([txt],{type:'text/plain'}); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = fn.replace(/[^a-z0-9]/gi,'_')+'_notes.txt'; a.click(); URL.revokeObjectURL(url); toggleModal('exportModal', false); showToast('TXT exported!'); });
  document.getElementById('exportPdfBtn').addEventListener('click', () => { const fe = entries.filter(e => e.folderId === currentFolderId && e.content.trim() !== ''); if (fe.length === 0) { showToast('No notes to export'); return; } const fn = getFolderName(currentFolderId); const pw = window.open('','_blank'); if (!pw) { showToast('Pop-up blocked'); return; } pw.document.title = fn+' - Jigsaw Notes'; const st = pw.document.createElement('style'); st.textContent = 'body{font-family:system-ui,sans-serif;padding:40px;max-width:700px;margin:0 auto;color:#222}h1{font-size:22px;border-bottom:2px solid #4cd36f;padding-bottom:8px}.note{margin:20px 0;padding:16px;border:1px solid #ddd;border-radius:8px;page-break-inside:avoid}.note-cat{font-size:11px;text-transform:uppercase;color:#4cd36f;font-weight:700}.note-content{white-space:pre-wrap;font-size:14px;line-height:1.6;margin-top:8px}.footer{font-size:11px;color:#999;margin-top:40px;text-align:center}'; pw.document.head.appendChild(st); let bodyHtml = '<h1>'+escapeHTML(fn)+'</h1>'; fe.forEach(e => { const cn = getCats(e.catIds).map(c=>c.name).join(', '); bodyHtml += '<div class="note"><div class="note-cat">'+escapeHTML(cn)+'</div><div class="note-content">'+escapeHTML(e.content)+'</div></div>'; }); bodyHtml += '<div class="footer">Exported from Jigsaw Notes \u00b7 '+new Date().toLocaleString()+'</div>'; pw.document.body.innerHTML = bodyHtml; setTimeout(() => pw.print(), 300); toggleModal('exportModal', false); showToast('PDF ready \u2014 use print dialog to save'); });
  document.getElementById('editorPinBtn').addEventListener('click', () => { if (!currentNoteId) return; if (pinnedNotes.includes(currentNoteId)) { pinnedNotes = pinnedNotes.filter(id => id !== currentNoteId); showToast('Note unpinned'); } else { pinnedNotes.push(currentNoteId); showToast('Note pinned'); } saveAll(); updateEditorUI(); });
  document.getElementById('fmtBold').addEventListener('click', () => formatText('**'));
  document.getElementById('fmtItalic').addEventListener('click', () => formatText('*'));
  document.getElementById('fmtUnder').addEventListener('click', () => formatText('__'));
  document.getElementById('fmtStrike').addEventListener('click', () => formatText('~~'));
  document.getElementById('noteContent').addEventListener('keydown', e => { const triggers = [' ','Enter',',','.',';',':','!','?']; if (!triggers.includes(e.key)) return; const ta = e.target, val = ta.value, pos = ta.selectionStart; let ws = pos; while (ws > 0 && val[ws-1] !== ' ' && val[ws-1] !== '\n') ws--; const word = val.slice(ws, pos); if (!word) return; const folder = folders.find(f => f.id === currentFolderId); if (folder && folder.shorthandEnabled === false) return; const allowed = dict.filter(en => isEntryAllowedInFolder(en, currentFolderId)); const me = allowed.find(en => en.key.toLowerCase() === word.toLowerCase()); if (!me) return; e.preventDefault(); const ic = e.key === 'Enter' ? '\n' : e.key; ta.value = val.slice(0,ws)+me.val+ic+val.slice(pos); const np = ws+me.val.length+1; ta.setSelectionRange(np,np); autoSaveNote(); });
  document.getElementById('noteContent').addEventListener('input', autoSaveNote);
  document.getElementById('rapidAddBtn').addEventListener('click', addRapidEntry);
  document.getElementById('rapidEntry').addEventListener('keydown', e => { if (e.key === 'Enter') document.getElementById('rapidAddBtn').click(); });
  document.getElementById('addFolderBtn').addEventListener('click', () => { const name = document.getElementById('newFolderInput').value.trim(); if (!name) return; const newId = 'f_'+Date.now().toString(36); folders.push({id:newId,name,parentId:document.getElementById('newFolderParent').value,shorthandEnabled:true}); saveAll(); document.getElementById('newFolderInput').value = ''; renderSidebarFolders(); });
  document.getElementById('catAdd').addEventListener('click', () => { const name = document.getElementById('catName').value.trim(), prefix = document.getElementById('catPrefix').value.trim(); if (name) { let ex = categories.find(c => c.name.toLowerCase() === name.toLowerCase()); if (ex) ex.prefix = prefix; else categories.push({id:'cat_'+Date.now().toString(36),name,prefix}); saveAll(); renderCategories(); document.getElementById('catName').value = ''; document.getElementById('catPrefix').value = ''; } });
  document.getElementById('menuBinBtn').addEventListener('click', () => { renderBinModal(); toggleModal('binModal', true); });
  document.getElementById('closeBinBtn').addEventListener('click', () => toggleModal('binModal', false));
  autoPurgeBin(); updateBinBadge(); switchView('rapid');
  if (window.visualViewport) { const dock = document.getElementById('bottom-dock'); function udp() { const kh = Math.max(0, window.innerHeight - window.visualViewport.height - (window.visualViewport.offsetTop||0)); dock.style.bottom = kh+'px'; } window.visualViewport.addEventListener('resize', udp); window.visualViewport.addEventListener('scroll', udp); }
};
